### ISSUE TITLE
Acquire Token after period of inactivity.

### ISSUE THREAD

**Issue by clyde-hoang** [benbaran/adal-angular4#79]
Hi All,

I was hoping someone is able to give me a hand in resolving the following issue.

I've recently update my angular6 app to take advantage of the latest features in adal-angular4 (v3.0.7), mainly the automatic renewal of access tokens/id tokens. After logging in and usage of the app for several hours (~8 hours) the application is working fine and I'm also using the id token for authorization against a web api resource.

Around ~10 hours+, leaving my computer idle the access token and id token become stale. When calling my web api the api returns a 401 due to the invalid access token. As an attempted solution I've introduced an additional timer(every minute) to call the acquireToken('client_id') for the given resource if the token is invalid. The acquireToken function occasionally returns a failure message 'Token renewal operation failed due to timeout'.

I've read the implementation for the azure implicit grant flow for the 'renewal' token process works as follows: The client application is able to acquire as many access tokens as long as the Azure AD User session is valid. My question is this something I should configure on Azure AD regarding token lifetimes or is this a issue with the adal-angular4 library? Any help would be greatly appreciated!!

Also the reason why I need the access token to be so long living is we are trying to implement a 'stay logged in feature'.

**Comment by jo-me** [comment]
I'm seeing the same issue here.. 
I thought the timer would auto-renew the id token..

Do you know if the implicit grant flow has to be enabled in AAD?

**Comment by geerzo** [comment]
@clyde-hoang there are a couple things are at work here so let me ask a couple questions (assuming no second timer you implemented)
1) At the 10+ hour mark, does the built in time stop working? Or does the renew call fail for the idtoken? (it's whole goal is the renew the idtoken)
2) "Stay logged in" is really a feature of AAD and the session with that. As long as the session is still valid your app should be able to "stay logged in". So at that 10+ hour mark, if you navigate to another app protected by the same AAD user is it logged in or require re-login (i.e. did the session expire)

**Comment by geerzo** [comment]
BTW - I did find a bug where the refresh timer wasn't being initiated on the initial login, only on a reload of the app after being logged in. I have a fix for that I'll check in tomorrow after doing some additional testing around the issue you described above on stopping working after a period of time.

**Comment by geerzo** [comment]
Fixed the issue with the timer not starting after a fresh login. Fixed here ecf866607cd51b74727da38daba0b3c0d87a81ae

I also ran some tests and saw that my timer, using the example project, ran for over 24 hours and kept the token fresh.

**Comment by danwale** [comment]
Thanks for the fix, do we know when this will be pushed out to the npm package published on npm.js? The last published version is still version 3.0.13 so we're still seeing this issue.

**Comment by benbaran** [comment]
Sorry, I missed this. I’ll try to publish tomorrow!
